# Generated by Django 3.2.6 on 2021-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifield',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apifield',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apifield',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
